name: Check Rive-Android sub modules

on:
  # lets check it when we push to master (we've just done something in android, its a good time to see about this)
  push:
    branches:
      - master
  
  schedule:
    # 8am UTC every day
    - cron:  '0 8 * * *'


jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run cpp version check 
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: sh ./.github/scripts/rive_cpp_check.sh